/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orderingsystemforsanti;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class InventoryForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventoryForm.class.getName());

    /**
     * Creates new form InventoryForm
     */
    public InventoryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LEFT = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jLabelProducts = new javax.swing.JLabel();
        jLabelManageUser = new javax.swing.JLabel();
        jLabelInventory = new javax.swing.JLabel();
        jLabelHistory = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LEFT.setBackground(new java.awt.Color(51, 51, 0));
        LEFT.setForeground(new java.awt.Color(102, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystemforsanti/logo (1).png"))); // NOI18N

        jLabelHome.setFont(new java.awt.Font("Nirmala Text", 0, 24)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(0, 255, 255));
        jLabelHome.setText("Home");
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });

        jLabelProducts.setFont(new java.awt.Font("Nirmala Text", 0, 24)); // NOI18N
        jLabelProducts.setForeground(new java.awt.Color(0, 255, 255));
        jLabelProducts.setText("Products");
        jLabelProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductsMouseClicked(evt);
            }
        });

        jLabelManageUser.setFont(new java.awt.Font("Nirmala Text", 0, 24)); // NOI18N
        jLabelManageUser.setForeground(new java.awt.Color(0, 255, 255));
        jLabelManageUser.setText("Manage User");
        jLabelManageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelManageUserMouseClicked(evt);
            }
        });

        jLabelInventory.setFont(new java.awt.Font("Nirmala Text", 0, 24)); // NOI18N
        jLabelInventory.setForeground(new java.awt.Color(0, 255, 255));
        jLabelInventory.setText("Inventory");
        jLabelInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInventoryMouseClicked(evt);
            }
        });

        jLabelHistory.setFont(new java.awt.Font("Nirmala Text", 0, 24)); // NOI18N
        jLabelHistory.setForeground(new java.awt.Color(0, 255, 255));
        jLabelHistory.setText("History");
        jLabelHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHistoryMouseClicked(evt);
            }
        });

        jButtonLogout.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 51, 51));
        jButtonLogout.setText("Logout");
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseClicked(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Welcome, Admin!");

        javax.swing.GroupLayout LEFTLayout = new javax.swing.GroupLayout(LEFT);
        LEFT.setLayout(LEFTLayout);
        LEFTLayout.setHorizontalGroup(
            LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LEFTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LEFTLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LEFTLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelManageUser)
                                    .addComponent(jLabelProducts)
                                    .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelInventory)
                                    .addComponent(jLabelHistory)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );
        LEFTLayout.setVerticalGroup(
            LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LEFTLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(40, 40, 40)
                .addComponent(jLabelHome)
                .addGap(18, 18, 18)
                .addComponent(jLabelProducts)
                .addGap(18, 18, 18)
                .addComponent(jLabelManageUser)
                .addGap(18, 18, 18)
                .addComponent(jLabelInventory)
                .addGap(18, 18, 18)
                .addComponent(jLabelHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LEFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1018, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LEFT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void jLabelProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductsMouseClicked
        new ProductsForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelProductsMouseClicked

    private void jLabelManageUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelManageUserMouseClicked
        new ManageUserForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelManageUserMouseClicked

    private void jLabelInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInventoryMouseClicked
        new InventoryForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelInventoryMouseClicked

    private void jLabelHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHistoryMouseClicked
        new HistoryForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelHistoryMouseClicked

    private void jButtonLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonLogoutMouseClicked

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InventoryForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LEFT;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHistory;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelInventory;
    private javax.swing.JLabel jLabelManageUser;
    private javax.swing.JLabel jLabelProducts;
    // End of variables declaration//GEN-END:variables
}
